services:
  - type: web
    name: image-grabber
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: IPAPI_KEY
        sync: false
